In [11]:
# importar las librerias necesarias
import numpy as np
import pandas as pd
print("Clase 1 - Tema 1");

Clase 1 - Tema 1

In [14]:
# Simulador de datos de alguna situación real

# definir la semilla
np.random.seed(42)

# declarar la variable
tiempos = np.random.normal(loc=10, scale=2, size=1000)
tiempos = np.append(tiempos, [35,40])
df = pd.DataFrame({'tiempo_resolucion': tiempos})
df.head()

   tiempo_resolucion
0          10.993428
1           9.723471
2          11.295377
3          13.046060
4           9.531693

In [15]:
df.tail()

      tiempo_resolucion
997           11.281686
998            8.857642
999           11.145166
1000          35.000000
1001          40.000000

In [16]:
df

      tiempo_resolucion
0             10.993428
1              9.723471
2             11.295377
3             13.046060
4              9.531693
...                 ...
997           11.281686
998            8.857642
999           11.145166
1000          35.000000
1001          40.000000

[1002 rows x 1 columns]

In [17]:
print(df)

      tiempo_resolucion
0             10.993428
1              9.723471
2             11.295377
3             13.046060
4              9.531693
...                 ...
997           11.281686
998            8.857642
999           11.145166
1000          35.000000
1001          40.000000

[1002 rows x 1 columns]

In [21]:
media = df['tiempo_resolucion'].mean()
print(f"Media: {media:.2f} horas")

Media: 10.09 horas

In [22]:
mediana = df['tiempo_resolucion'].median()
print(f"mediana: {mediana:.2f} horas")

mediana: 10.05 horas

In [23]:
moda = df['tiempo_resolucion'].mode().iloc[0]
print(f"moda: {moda:.2f} horas")

moda: 3.52 horas

In [26]:
moda = df['tiempo_resolucion'].mode()
print(moda)

0        3.517465
1        4.606227
2        4.698060
3        4.760510
4        5.056711
          ...
997     15.440338
998     16.157762
999     17.705463
1000    35.000000
1001    40.000000
Name: tiempo_resolucion, Length: 1002, dtype: float64

In [32]:
maximo = df['tiempo_resolucion'].max()
minimo = df['tiempo_resolucion'].min()
print(f"maximo: {maximo:.2f} horas")
print(f"minimo: {minimo:.2f} horas")

maximo: 40.00 horas
minimo: 3.52 horas

In [33]:
rango = maximo - minimo
print(f"rango: {rango:.2f} horas")

rango: 36.48 horas

**Desviacion estandar**

In [31]:
desviacion = df['tiempo_resolucion'].std()
print(f"desviacion estandar: {desviacion:.2f} horas")

desviacion estandar: 2.31 horas

In [29]:
varianza = df['tiempo_resolucion'].var()
print(f"varianza: {varianza:.2f} horas")

varianza: 5.34 horas

In [34]:
coef_var = (desviacion / media) * 100
print(f"coeficiente de variacion: {coef_var:.2f} horas")

coeficiente de variacion: 22.90 horas

**Distribuciones discretas**

In [1]:
# bernouli
# bernoulli de scipy.stats para generar valores con la distribución de Bernoulli.
# matplotlib.pyplot para graficar resultados.
from scipy.stats import bernoulli
import matplotlib.pyplot as plt

Distribución de **Bernoulli**

In [2]:
# Probabilidad de autenticación exitosa
p = 0.92
# Simular 100 autenticaciones
resultados = bernoulli.rvs(p, size=100)
# Contar resultados
exitos = sum(resultados)
fallos = len(resultados) - exitos
print(f"Éxitos: {exitos}, Fallos: {fallos}")

# Se suman los valores 1 para contar los éxitos.
# Los fallos se calculan como el complemento (100 - éxitos).
# Se imprime un resumen de cuántos intentos funcionaron y cuántos fallaron.

Éxitos: 92, Fallos: 8

**Distribución Binomial**

In [3]:
from scipy.stats import binom
# Parámetros del problema
n = 20    # número de notificaciones
р = 0.75  # probabilidad de apertura 
k = 15    # éxitos deseados
# Calcular probabilidad de exactamente 15 aperturas 9. 
probabilidad = binom.pmf(k, n, p)
print(f"Probabilidad de exactamente {k} aperturas: {probabilidad:.4f}")

Probabilidad de exactamente 15 aperturas: 0.0145

**Distribución Normal**

In [5]:
from scipy.stats import norm
# Parámetros del problema
mu= 250     # media
sigma = 30  # desviación estándar
x = 300     # umbral deseado
# Calcular probabilidad de que la respuesta sea > 300 ms
probabilidad = 1 - norm.cdf(x, mu, sigma)
print(f"Probabilidad de respuesta > 300 ms: {probabilidad:.4%}")

Probabilidad de respuesta > 300 ms: 4.7790%

asdasd

In [6]:
import numpy as np
from scipy import stats
# Datos de muestra
tiempos = [12, 11, 13, 12, 14, 10, 11, 15, 13, 12]
n = len(tiempos)
media_muestra = np.mean(tiempos)
desv_std_muestra = np.std(tiempos, ddof=1) # ddof=1 para muestras

# Intervalo de confianza del 95%
confianza = 0.95
grados_libertad = n-1
error_estandar = desv_std_muestra / np.sqrt(n)

t_critico = stats.t.ppf((1 + confianza) / 2, df=grados_libertad)
margen_error = t_critico * error_estandar

lim_inf = media_muestra - margen_error
lim_sup = media_muestra + margen_error

print(f"Intervalo de confianza 95%: [{lim_inf:.2f}, {lim_sup:.2f}] días")

Intervalo de confianza 95%: [11.23, 13.37] días