In [3]:
import pandas as pd
import numpy as np

In [4]:
# definir los criterios y sus pesos
criterios = ['Costo', 'Calidad', 'Tiempo de entrega']
pesos = [0.40, 0.35, 0.25]

# definir los datos de los proveedores
datos = {
    'Proveedor': ['A', 'B', 'C'],
    'Costo': [10000, 12000, 11000],
    'Calidad': [8, 7, 9],
    'Tiempo de entrega': [5, 3, 4],
}

# crear un datafram
df = pd.DataFrame(datos)
df

  Proveedor  Costo  Calidad  Tiempo de entrega
0         A  10000        8                  5
1         B  12000        7                  3
2         C  11000        9                  4

In [5]:
# normalizamos los datos
df['Costo'] = df['Costo'].max() / df['Costo']
df['Calidad'] = df['Calidad'] / df['Calidad'].max()
df['Tiempo de entrega'] = df['Tiempo de entrega'].max() / df['Tiempo de entrega']
df

  Proveedor     Costo   Calidad  Tiempo de entrega
0         A  1.200000  0.888889           1.000000
1         B  1.000000  0.777778           1.666667
2         C  1.090909  1.000000           1.250000

In [7]:
# calcilo del valor esperado de cada proveedor
df['Puntuacion total'] = (df['Costo']  * pesos[0]) + (df['Calidad']  * pesos[1]) + (df['Tiempo de entrega']  * pesos[2])
df

  Proveedor     Costo   Calidad  Tiempo de entrega  Puntuacion total
0         A  1.200000  0.888889           1.000000          1.041111
1         B  1.000000  0.777778           1.666667          1.088889
2         C  1.090909  1.000000           1.250000          1.098864

In [8]:
# seleccionar el mejor proveedor
mejor_proveedor = df.loc[df['Puntuacion total'].idxmax()]
mejor_proveedor

Proveedor                   C
Costo                1.090909
Calidad                   1.0
Tiempo de entrega        1.25
Puntuacion total     1.098864
Name: 2, dtype: object